---
title: "Coding in Analysis and Research Survey - live dashboard"
output_dir: docs
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
    css: style.css
---


```{r setup, include=FALSE}
library(flexdashboard)
library(carsurvey)
library(plotly)
library(magrittr)
library(dplyr)
```

```{r outputs, include = FALSE}
date <- stringr::str_split(format(Sys.time()), " ", simplify=T)[1]
time <- stringr::str_split(format(Sys.time()), " ", simplify=T)[2]

data <- read.csv("../../CARS-data/latest_data.csv")
data <- data[3:nrow(data),] # Filter out empty rows

recode_vals <- list(
  "Department of Health and Social Care (excl. agencies)" = "DHSC",               
  "Ministry of Justice (excl. agencies)" = "MoJ",                                    
  "Office for National Statistics" = "ONS",                                        
  "Government Digital Service" = "GDS",                                     
  "Department for Education" = "DfE",                                                
  "Department for Transport (excl. agencies)"= "DfT",                       
  "Northern Ireland Statistics and Research Agency" = "NISRA",                       
  "Department for Business, Energy and Industrial Strategy (excl. agencies)" = "BEIS",
  "Department for Work and Pensions" = "DWP",                               
  "HM Revenue and Customs" = "HMRC",
  "Public Health England" = "PHE",                                                   
  "Office for Statistics Regulation" = "OSR",                                        
  "Ministry of Defence" = "MoD",                                                     
  "United Kingdom Statistics Authority" = "UKSA",                                     
  "Department for Digital, Culture, Media and Sport" = "DCMS",
  "Department for Environment, Food and Rural Affairs (excl. agencies)" = "DEFRA",
  "Cabinet Office (excl. agencies)" = "CO",
  "Department for International Trade" = "DIT",                 
  "Department for International Development" = "DfID",
  "Welsh Government" = "WG",
  "Ministry of Housing, Communities and Local Government (excl. agencies)" = "MHCLG",
  "Government Actuary's Department" = "GAD",
  "HM Treasury" = "HMT",
  "National Records of Scotland" = "NRS",
  "Centre for Environment, Fisheries and Aquaculture Science" = "CEFAS",
  "Health and Safety Executive" = "HSE",
  "Her Majesty's Courts and Tribunals Service" = "HM Courts and Tribunals Service",
  "Office of Rail and Road" = "ORR",
  "Defence Science and Technology Laboratory" = "DSTL",
  "Home Office (excl. agencies)" = "HO"
  )

data$Q1..Which.department.do.you.primarily.work.in. <- 
  dplyr::recode(
    data$Q1..Which.department.do.you.primarily.work.in., !!!recode_vals
  ) 

deps <- data$Q1..Which.department.do.you.primarily.work.in.
freqs <- data.frame(table(deps))
colnames(freqs) <- c("Organisation", "Frequency")
freqs <- freqs[freqs$Frequency > 4, ]
rownames(freqs) <- NULL
n_responses <- length(deps)
freqs$Organisation <- factor(freqs$Organisation, levels = freqs$Organisation)

output <- carsurvey::freqOutput(freqs, n = n_responses)


```

row 
---------------------------------------------------------------------

### Can you see your department below?

So far we've had `r n_responses` responses to the survey. We hope to get at least 20 responses each from as many organisations as possible. This will allow us to produce summary statistics for each of those organisations.

If an organisation is not listed below, that means we have fewer than 5 responses from that organisation.


row 
---------------------------------------------------------------------

### Chart
```{r chart}
order <- order(freqs$Frequency)
plot_labs <- as.character(freqs$Organisation)
plot_labs <- c(" ", plot_labs[order], "  ")
frequencies <- c(0, freqs$Frequency[order], 0)

f <- list(
  family = "Arial",
  size = 18,
  color = "#7f7f7f"
)

x <- list(
  title = "Count",
  titlefont = f
)
y <- list(
  title = "Organisation",
  titlefont = f,
  categoryorder = "array",
  categoryarray = plot_labs
)

plotly::plot_ly(
  x = frequencies,
  y = plot_labs,
  type = "bar",
  orientation = "h"
) %>% 
  add_segments(x = 20, xend = 20, y = " ", yend = "  ") %>%
    layout(xaxis = x, yaxis = y) %>% 
      layout(showlegend = F) %>%
        config(displayModeBar = F)
```

### Table

```{r table}
carsurvey::output_table(output)
```

row 
---------------------------------------------------------------------

### Last updated:

Date: `r date`
Time: `r time`